apiVersion: 1
groups:
  - name: les_alerts
    interval: 1m
    rules:
      - uid: ph_high
        title: High pH Level
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: water_ph > 7.5
              instant: true
        for: 1m
        annotations:
          summary: pH level too high
        labels:
          severity: warning
      - uid: low_do
        title: Low Dissolved Oxygen
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            model:
              expr: dissolved_oxygen_mg_per_l < 5
              instant: true
        for: 1m
        annotations:
          summary: Dissolved oxygen below safe threshold
        labels:
          severity: critical
